---
name: ouroboros
description: OuroborOS, a custom ublue spin.

# The PC will need nvidia; the laptop probably not. Need to look into splitting
# it somehow.
base-image: ghcr.io/ublue-os/bluefin-dx-nvidia
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
        # TODO: create docker daemon.json with network overrides (or get used to
        # podman) and other system config stuff.

  # TODO: boxes, tuxguitar, eyedropper
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
          - org.gnome.Boxes
          - org.gnome.Extensions
          - ar.com.tuxguitar.TuxGuitar
          - org.jabref.jabref
          - com.github.finefindus.eyedropper
          - com.valvesoftware.Steam
          - md.obsidian.Obsidian
          - org.kde.filelight
          - org.chromium.Chromium
          - org.signal.Signal
          - com.spotify.Client
          - org.libreoffice.LibreOffice
      - scope: user

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  # TODO: this is copy-paste, package names might not match dnf
  - type: dnf
    install:
      packages:
        # Essentials
        - vim
        - wget
        - git
        - git-delta

        # Gnome stuff
        - gnome-tweaks
        # TODO: do we want this terminal instead of the built-in of bluefin?
        - gnome-terminal

        # CLI
        - bat
        - pass
        - pandoc
        - xclip
        - tree
        - htop
        - ncdu
        - zip
        - jq

        # Latex
        - hunspell
        - hunspell-en
        - hunspell-en-US
        - hunspell-en-GB
        - texlive-scheme-full
        # TODO: check if java is needed for ltex


        # Dev stuff. This is for some quick-and-dirty scripting. Full-on
        # projects go into a container.
        - python3
        - distrobox
        - dotnet-sdk-9.0

        # Virtualization
        # Docker is already part of bluefin, installing it manually errors out.
        # Leaving it here should I swap base images later on.
        # - docker-cli
        # - docker-compose
        - podman
        - podman-compose

  - type: gnome-extensions
    install:
      - Blur my Shell
      - AppIndicator and KStatusNotifierItem Support
      - Caffeine
      - Dash to Dock
      - RunCat

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode

  - type: containerfile
    snippets:
      # DuckDB isn't available with dnf yet, and I don't want to add some random
      # copr. No fan of the pipe into sh, but it'll do for now..
      # TODO: customize this and install to /usr/local/bin instead. See
      # https://duckdb.org/docs/installation for download link.
      - RUN curl https://install.duckdb.org | sh

# TODO: set up qwerty-fr layout
# https://github.com/qwerty-fr/qwerty-fr/issues/49#issuecomment-1405254634 if needed

# TODO: check gschema-overrides for interesting stuff.

# TODO: systemd config
# DefaultTimeoutStopSec=10s
# killMode mixed

# TODO journald config
# SystemMaxUse=50M

# TODO: set LC_TIME to nl_BE.UTF-8, TZ to Europe/Brussels
