---
name: ouroborOS
description: Custom ublue spin.

base-image: ghcr.io/ublue-os/bluefin-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
        # TODO: create docker daemon.json with network overrides (or get used to
        # podman)

  - type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks

  # TODO: boxes, tuxguitar, eyedropper
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  # TODO: this is copy-paste, package names might not match dnf
  - type: dnf
    install:
      packages:
        # Essentials
        - vim
        - wget
        - git
        - git-delta

        # Gnome stuff
        - gnome-tweaks
        # TODO: do we want this terminal instead of the built-in of bluefin?
        - gnome-terminal
        - gnome-extensions-app
        # TODO: move these to the gnome-extensions module
        - gnome-shell-extension-blur-my-shell
        - gnome-shell-extension-caffeine
        - gnome-shell-extension-dash-to-dock
        - gnome-shell-extension-runcat

        # CLI
        - bat
        - pass
        - pandoc
        - xclip
        - tree
        - htop
        - ncdu
        - zip
        - jq

        # Apps
        # TODO: move these to flatpaks where possible
        - chromium
        - obsidian
        - signal-desktop
        - kdePackages.filelight
        - spotify
        - libreoffice
        - jabref

        # Latex
        - hunspell
        - hunspellDicts.en_US
        - hunspellDicts.en_GB-large
        - texliveFull
        # TODO: check if java is needed for ltex


        # Fonts
        # TODO: there is a font module
        - fira-code
        - fira-code-symbols

        # Dev
        - python3Full
        - duckdb
        - distrobox
        # TODO: dotnet

# TODO: set up qwerty-fr layout
# https://github.com/qwerty-fr/qwerty-fr/issues/49#issuecomment-1405254634 if needed

# TODO: check gschema-overrides for interesting stuff.

# TODO: systemd config
# DefaultTimeoutStopSec=10s
# killMode mixed

# TODO journald config
# SystemMaxUse=50M

# TODO: set LC_TIME to nl_BE.UTF-8, TZ to Europe/Brussels
